name: BM20 Publish JSON to Pages

on:
  workflow_dispatch:        # 수동 실행
  schedule:
    - cron: "20 23 * * *"   # 매일 08:20 KST (23:20 UTC)

permissions:
  contents: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Copy latest output to docs/
        run: |
          set -euo pipefail
          SITE_SRC="docs"
          mkdir -p "$SITE_SRC"

          # 가장 최근 out/DATE 디렉토리 찾기
          LAST_DIR=$(ls -d out/* 2>/dev/null | sort -r | head -n 1 || true)
          if [ -z "${LAST_DIR:-}" ] || [ ! -d "$LAST_DIR" ]; then
            echo "No out/DATE directory found"; exit 0
          fi
          echo "Found latest output dir: $LAST_DIR"

          copy_if_exists () {
            SRC="$1"; DST="$2"
            if [ -f "$SRC" ]; then
              cp "$SRC" "$SITE_SRC/$DST"
              echo "✓ $SRC -> $SITE_SRC/$DST"
            fi
          }

          copy_if_exists "$LAST_DIR/latest.json" latest.json
          copy_if_exists "$LAST_DIR/bm20_latest.json" latest.json

          copy_if_exists "$LAST_DIR/series.json" series.json
          copy_if_exists "$LAST_DIR/bm20_series.json" series.json
          copy_if_exists "$LAST_DIR/bm20_index_history.json" series.json

          copy_if_exists "$LAST_DIR/contrib_top.json" contrib_top.json
          copy_if_exists "$LAST_DIR/bm20_contrib_top.json" contrib_top.json

          for f in bm20_bar_latest.png bm20_trend_latest.png; do
            if [ -f "$LAST_DIR/$f" ]; then
              cp "$LAST_DIR/$f" "$SITE_SRC/$f"
              echo "✓ $LAST_DIR/$f -> $SITE_SRC/$f"
            fi
          done

      - name: Commit & Push
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add docs/
          git commit -m "Publish BM20 JSON to docs/" || echo "No changes"
          git push
