title: "BM Indices"

url: "https://ceciliamyeong.github.io"
baseurl: "/bm"            # 리포 이름이 bm일 때 필수

# 테마 제거: 커스텀 `_layouts/default.html` 사용
# theme: minima

# 블로그 기능 안 쓰면 생략
markdown: kramdown
kramdown:
  input: GFM

# GitHub Pages 기본 플러그인 외 추가 없음
plugins: []

# (선택) permalink 기본 패턴 — 페이지(front matter의 permalink)가 우선
permalink: pretty

# ▼▼▼ 여기부터 추가 ▼▼▼
include:
  - latest.html
  - api        # 폴더 전체 포함 (와일드카드 불필요)
  - archive 

