name: Build BM20 Backfill

on:
  workflow_dispatch:
  schedule:
    - cron: "10 22 * * *"   # KST 07:10 = UTC 22:10

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install yfinance pandas numpy

      - name: Run backfill + export JSON
        run: |
          mkdir -p out
          python backfill_current_basket.py \
            --archive ./archive \
            --map bm20_map_btc30.csv \
            --start 2018-01-01 \
            --out out/backfill_current_basket.csv
          # 위 스크립트 끝부분에서 자동으로 bm20_series.json, bm20_latest.json 생성됨

      - name: Commit & Push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add bm20_series.json bm20_latest.json
          git commit -m "update BM20 JSON ($(date -u +'%Y-%m-%dT%H:%M:%SZ'))" || echo "No changes"
          git push
