title: "BM Indices"
baseurl: "/bm"   # ← 리포 이름이 bm 이면 반드시 /bm

nav:
  - text: "BM20 개요"
    url: "/bm20/"               # 개요(차트) 페이지
  - text: "BM20 구성"
    url: "/bm20/weights/"       # 또는 "/bm20/portfolio-2025q3/" 로 연결해도 됩니다
