title: BM Indices
theme: minima

url: https://ceciliamyeong.github.io
baseurl: /bm          # ← 꼭!

header_pages:         # 헤더 메뉴에 올릴 문서 경로(사이트 루트 기준)
  - bm20/overview.md
  - bm20/components.md
  - bm20/daily-template.md
