name: BM20 Index Daily

on:
  schedule:
    - cron: "10 22 * * *"   # 매일 07:10 KST (UTC 22:10)
  workflow_dispatch:

concurrency:
  group: bm20-index-daily
  cancel-in-progress: false

permissions:
  contents: read

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      SHEET_ID: ${{ secrets.SHEET_ID }}
      GOOGLE_SERVICE_ACCOUNT_JSON: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps
        run: pip install pandas numpy yfinance gspread google-auth google-auth-oauthlib google-auth-httplib2
      - name: Append today's index (live)
        run: python scripts/run_daily.py
