name: BM20 Daily

on:
  schedule:
    - cron: "05 22 * * *"  # 07:05 KST (UTC 22:05)
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      SHEET_ID: ${{ secrets.SHEET_ID }}
      GOOGLE_SERVICE_ACCOUNT_JSON: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps
        run: pip install gspread google-auth google-auth-oauthlib google-auth-httplib2
      - name: Run daily updater
        run: python scripts/run_daily.py
