name: BM20 data (CSV→Index→JSON commit)

on:
  workflow_dispatch:
  schedule:
    - cron: '30 22 * * *'  # 07:30 KST

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Prepare dirs
        run: |
          mkdir -p out bm/api

      # 1) CSV 아카이브 → 인덱스 재계산 (out/)
      - name: Build index from CSVs
        run: |
          python bm20_from_daily_csv.py \
            --archive ./archive \
            --out ./out \
            --rebalance quarterly \
            --weights-source rules \
            --listed-bonus 1.3 \
            --cap BTC:0.30 --cap ETH:0.20 \
            --map bm20_map_btc30.csv
          ls -l out || true

      # 2) 웹에서 바로 쓰는 JSON(+CSV 사본) 생성 → bm/api/
      - name: Export JSON/CSV for web (bm/api)
        run: |
          python export_json.py out/bm20_index_from_csv.csv bm/api
          cp -f out/bm20_index_from_csv.csv bm/api/bm20_index_from_csv.csv
          echo "---- bm/api ----"
          find bm/api -maxdepth 1 -type f -print | sort || true

      # 3) 레포에 커밋 & 푸시 (브랜치 배포 방식 유지, 페이지 덮어쓰기 없음)
      - name: Commit & push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "[skip ci] data: update BM20 API $(date -u +'%Y-%m-%dT%H:%M:%SZ')" || echo "No changes to commit"
          git push origin main

