name: BM20 Latest2 Publish

on:
  workflow_dispatch:
    inputs:
      script:
        description: "Which script to run"
        type: choice
        required: true
        options:
          - bm20_daily.py
          - bm20_daily_v2.py
        default: bm20_daily_v2.py
      date:
        description: "YYYY-MM-DD (empty = today in KST)"
        type: string
        required: false

  schedule:
    - cron: "10 23 * * *"   # 23:10 UTC = 08:10 KST (원하면 조정)

jobs:
  build-and-publish-latest2:
    runs-on: ubuntu-latest
    concurrency:
      group: bm20-latest2
      cancel-in-progress: false

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            pip install pandas numpy requests matplotlib reportlab jinja2 yfinance
          fi

      - name: Run BM20 script
        env:
          TZ: Asia/Seoul
          OUT_DIR: out
          BM20_DATE: ${{ inputs.date }}
        run: |
          set -e
          python "${{ inputs.script }}"

      - name: Resolve DATE & SRC folder
        id: resolve
        shell: bash
        run: |
          set -e
          if [ -n "${{ inputs.date }}" ]; then
            DATE="${{ inputs.date }}"
          else
            DATE=$(ls -1d out/*/ 2>/dev/null | awk -F'/' '{print $(NF-1)}' | sort | tail -n1)
          fi
          echo "DATE=$DATE" >> $GITHUB_ENV
          echo "SRC=out/$DATE" >> $GITHUB_ENV

      - name: Prepare latest2 assets
        run: |
          set -e
          mkdir -p latest2/assets/"$DATE"
          # 필수 파일 경로
          HTML="$SRC/bm20_daily_${DATE}.html"
          PDF="$SRC/bm20_daily_${DATE}.pdf"
          CSV="$SRC/bm20_daily_data_${DATE}.csv"
          TXT="$SRC/bm20_news_${DATE}.txt"
          BAR="$SRC/bm20_bar_${DATE}.png"
          TRD="$SRC/bm20_trend_${DATE}.png"

          # latest2용 파일 복사
          cp "$BAR" bm20_bar_latest2.png
          cp "$TRD" bm20_trend_latest2.png
          cp "$HTML" "latest2/assets/${DATE}/" || true
          cp "$PDF"  "latest2/assets/${DATE}/" || true
          cp "$CSV"  "latest2/assets/${DATE}/" || true

          # 뉴스 텍스트를 HTML로 이스케이프
          python - <<'PY' > news.html
          import os, html, sys
          p=os.environ.get("TXT")
          if p and os.path.exists(p):
              s=open(p,encoding="utf-8").read()
              sys.stdout.write(html.escape(s).replace("\n","<br/>"))
          else:
              sys.stdout.write("데이터 없음")
          PY

      - name: Render latest2.html from template
        run: |
          set -e
          TPL="latest2.template.html"
          [ -f "$TPL" ] || { echo "template not found: $TPL"; exit 1; }
          NEWS_HTML=$(cat news.html)
          # 간단 치환(뉴스는 특수문자·줄바꿈 이미 HTML 처리됨)
          sed -e "s/{{DATE}}/${DATE}/g" -e "s#{{NEWS_HTML}}#${NEWS_HTML}#g" "$TPL" > latest2.html

      - name: Commit & Push latest2
        run: |
          git config user.name  "bm20-bot"
          git config user.email "bm20-bot@users.noreply.github.com"
          git add latest2.html bm20_bar_latest2.png bm20_trend_latest2.png latest2/assets/
          git commit -m "Publish latest2 for ${DATE}" || echo "no changes"
          git push
