name: BM20 Daily @ 8AM KST

on:
  schedule:
    # GitHub Actions uses UTC. KST 08:00 = previous day 23:00 UTC
    - cron: "0 23 * * *"
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Seoul
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install requests matplotlib pandas

      - name: Generate daily report (archive + latest)
        run: |
          python scripts/generate_report.py

      - name: Commit & push
        uses: EndBug/add-and-commit@v9
        with:
          add: |
            index.html
            archive/
            archive/index.html
          message: "chore: auto daily report"
