name: Publish Top5 JSON

on:
  schedule:
    - cron: '5 22 * * *' # 서울 07:05
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install requests pandas
      - name: Generate JSON
        run: python scripts/upbit_publish_json.py
      - name: Commit & push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add assets/top5/*.json
          git commit -m "Update Top5 JSON [skip ci]" || echo "No changes"
          git pull --rebase
          git push
